# Generated by Django 3.2.6 on 2022-11-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='%Y/%m/%d'),
        ),
    ]
